query HomeContent {
	site: _site {
		favicon: faviconMetaTags {
			attributes
			content
			tag
		}
	}

	blog {
		seo: _seoMetaTags {
			attributes
			content
			tag
		}
	}

	allPosts(orderBy: date_DESC, first: 20) {
		title
		slug
		excerpt
		date
		coverImage {
			...ImageFragment
		}
		author {
			...AuthorFragment
		}
	}
}
