query PostContent($slug: String) {
	site: _site {
		favicon: faviconMetaTags {
			attributes
			content
			tag
		}
	}

	post(filter: { slug: { eq: $slug } }) {
		seo: _seoMetaTags {
			attributes
			content
			tag
		}
		title
		slug
		content {
			value
			blocks {
				__typename
				... on ImageBlockRecord {
					id
					image {
						responsiveImage(imgixParams: { fm: jpg, fit: crop, w: 2000, h: 1000 }) {
							src
							width
							height
							alt
							title
						}
					}
				}
			}
		}
		date
		ogImage: coverImage {
			url(imgixParams: { fm: jpg, fit: crop, w: 2000, h: 1000 })
		}
		coverImage {
			responsiveImage(imgixParams: { fm: jpg, fit: crop, w: 2000, h: 1000 }) {
				src
				width
				height
				alt
				title
			}
		}
		author {
			name
			picture {
				responsiveImage(imgixParams: { fm: jpg, fit: crop, w: 100, h: 100, sat: -100 }) {
					src
					width
					height
					alt
					title
				}
			}
		}
	}

	morePosts: allPosts(orderBy: date_DESC, first: 2, filter: { slug: { neq: $slug } }) {
		title
		slug
		excerpt
		date
		coverImage {
			responsiveImage(imgixParams: { fm: jpg, fit: crop, w: 2000, h: 1000 }) {
				src
				width
				height
				alt
				title
			}
		}
		author {
			name
			picture {
				responsiveImage(imgixParams: { fm: jpg, fit: crop, w: 100, h: 100, sat: -100 }) {
					src
					width
					height
					alt
					title
				}
			}
		}
	}
}
